### ISSUE TITLE
Regra 8 - Critério desempate - Mão de ferro

### ISSUE THREAD

**Issue by ThiagoValcacio** [ThiagoValcacio/PDS2#17]
Eu, como usuário, quero que quando o jogo esteja empatado em 10 a 10 (mantendo as regras da mão de dez, declaradas na regra 7), o jogo entre no modo mão de ferro, ou seja, nenhum jogador tem acesso às cartas apenas jogando-as no "escuro".

**Comment by TassoossaT** [comment]
Criterio de desempate Mão de ferro 

> Requerimentos

- ambas duplas estarem com exatamente 10 pontos.

> Critérios de aceitação

- Dupla que começa escolhe as opões:

- [ ] - jogar na mão de ferro #17
- [ ] - seguir para regra de 10 normal #16 

> Opções de implementação 

- [ ] mudar/adicionar criterio de - aceitação #16 para **Apenas uma das duplas deve ter atingido a marca de 10 pontos ou as duas duplas estarem com os 10 pontos e a primeira dupla não quer jogar a mão de ferro**
- [ ] tirar a opção de escolha do jogador 

> Restrições
- opção de truco desativada
